### ISSUE TITLE
Interval comparisons with `simd` feature asserts

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1136]
**Describe the bug**

When @tustvold implemented basic support for interval comparison kernels in https://github.com/apache/arrow-rs/pull/1107, the test fails with the `simd` feature enabled.

https://github.com/apache/arrow-rs/runs/4719580675?check_suite_focus=true

```
---- compute::kernels::comparison::tests::test_interval_array stdout ----
thread 'compute::kernels::comparison::tests::test_interval_array' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `0`: Number of vector lanes must be multiple of 8', arrow/src/compute/kernels/comparison.rs:1517:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/core/src/panicking.rs:182:23
   3: core::panicking::assert_failed
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/core/src/panicking.rs:145:5
   4: arrow::compute::kernels::comparison::simd_compare_op
             at ./src/compute/kernels/comparison.rs:1517:5
   5: arrow::compute::kernels::comparison::lt
             at ./src/compute/kernels/comparison.rs:1937:12
   6: arrow::compute::kernels::comparison::tests::test_interval_array
             at ./src/compute/kernels/comparison.rs:2786:19
   7: arrow::compute::kernels::comparison::tests::test_interval_array::{{closure}}
             at ./src/compute/kernels/comparison.rs:2763:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/acbe4443cc4c9695c0b74a7b64b60333c990a400/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with RUST_BACKTRACE=full` for a verbose backtrace.
```

**To Reproduce**
Run the test mentioned above with the simd feature enabled (after first removing the `cfg` directive):

```rust
    #[cfg(not(feature = "simd"))]
```

**Expected behavior**
test should pass

**Additional context**
I am not familiar with the simd feature to know the best way to fix this, so filing a ticket instead.

**Comment by jhorstmann** [comment]
The issue seems to be with the relatively new `MonthDayNano` interval type, which is stored as `i128`. The simd machinery does not yet support that type, since it works with 512bits at a time it assumed a minimum of 8 lanes (for 64bit types). I'll check how easy it would be to extend that.
