### ISSUE TITLE
Flaky Integration Test

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1579]
**Describe the bug**

The integration tests appear to be flaky

**To Reproduce**

Initially the integration test failed

https://github.com/apache/arrow-rs/actions/runs/2179407062

Re-running the pipeline it succeeded

https://github.com/apache/arrow-rs/runs/6053020384?check_suite_focus=true

**Expected behavior**

The integration tests should consistently succeed or fail

**Comment by alamb** [comment]
https://github.com/apache/arrow-rs/actions/runs/2179407062 says passed now

Maybe github updated the output

**Comment by tustvold** [comment]
That is remarkably unhelpful, it shows that the run was re-attempted but is not particularly clear on how to view the failed attempt 🤦‍♂️

**Comment by tustvold** [comment]
Ok, turns out you need to be logged in to see the previous attempts and I was on a mobile. 

You can select previous attempts from the drop-down in the top-right

![image](https://user-images.githubusercontent.com/1781103/163806053-99065e03-4c67-4acf-9c0d-f82560cb3cee.png)

Link to the failed run is here

https://github.com/apache/arrow-rs/actions/runs/2179407062/attempts/1

**Comment by alamb** [comment]
For future ease of discussion, the failure mode appears to be:

```
==========================================================
Testing file duration
==========================================================
Traceback (most recent call last):
################# FAILURES #################
FAILED TEST: interval_mdn Go producing,  Go consuming

1 failures
  File "/arrow/dev/archery/archery/integration/util.py", line 139, in run_cmd
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/opt/conda/envs/arrow/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/arrow/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/go/bin/arrow-flight-integration-client', '-host', 'localhost', '-port=41991', '-path', '/tmp/arrow-integration-u1u9ty31/generated_interval_mdn.json']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/arrow/dev/archery/archery/integration/runner.py", line 379, in _run_flight_test_case
    consumer.flight_request(port, **client_args)
  File "/arrow/dev/archery/archery/integration/tester_go.py", line 121, in flight_request
    run_cmd(cmd)
  File "/arrow/dev/archery/archery/integration/util.py", line 148, in run_cmd
    raise RuntimeError(sio.getvalue())
RuntimeError: Command failed: /opt/go/bin/arrow-flight-integration-client -host localhost -port=41991 -path /tmp/arrow-integration-u1u9ty31/generated_interval_mdn.json
With output:
--------------
Opening JSON file ' /tmp/arrow-integration-u1u9ty31/generated_interval_mdn.json '
Opening JSON file ' /tmp/arrow-integration-u1u9ty31/generated_interval_mdn.json '
Opening JSON file ' /tmp/arrow-integration-u1u9ty31/generated_interval_mdn.json '
panic: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:41991: connect: connection refused"

goroutine 1 [running]:
main.main()
	/arrow/go/arrow/internal/flight_integration/cmd/arrow-flight-integration-client/main.go:52 +0x31a

--------------

1
Error: `docker-compose --file /home/runner/work/arrow-rs/arrow-rs/docker-compose.yml run --rm -e ARCHERY_INTEGRATION_WITH_RUST=1 conda-integration` exited with a non-zero exit code 1, see the process log above.

The docker-compose command was invoked with the following parameters:

```
