### ISSUE TITLE
Intermittent Flight integration test failures

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#201]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11908

This is similar to the symptoms seen in ARROW-11717 but it is still happening  intermittently

On two separate PR I see similar failures:
https://github.com/apache/arrow/pull/9645/checks?check_run_id=2052183132
https://github.com/apache/arrow/pull/9647/checks?check_run_id=2051946608

Example failure:

{code}

subprocess.CalledProcessError: Command '['/build/cpp/debug/flight-test-integration-client', '-host', 'localhost', '-port=41743', '-scenario', 'auth:basic_proto']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/arrow/dev/archery/archery/integration/runner.py", line 308, in _run_flight_test_case
    consumer.flight_request(port, **client_args)
  File "/arrow/dev/archery/archery/integration/tester_cpp.py", line 116, in flight_request
    run_cmd(cmd)
  File "/arrow/dev/archery/archery/integration/util.py", line 148, in run_cmd
    raise RuntimeError(sio.getvalue())
RuntimeError: Command failed: /build/cpp/debug/flight-test-integration-client -host localhost -port=41743 -scenario auth:basic_proto
With output:
--------------
-- Arrow Fatal Error --
Invalid: Expected UNAUTHENTICATED but got Unavailable

--------------

################# FAILURES #################
FAILED TEST: auth:basic_proto Rust producing,  C++ consuming

{code}

**Comment by alamb** [comment]
Comment from David Li(lidavidm) @ 2021-03-16T12:01:32.058+0000:
<pre>[~alamb] are you taking a look at this? Otherwise I'll add a retry on the C++ side.</pre>

Comment from Antoine Pitrou(apitrou) @ 2021-03-22T14:09:37.405+0000:
<pre>Issue resolved by pull request 9755
[https://github.com/apache/arrow/pull/9755]</pre>

Comment from Antoine Pitrou(apitrou) @ 2021-03-22T14:10:31.314+0000:
<pre>Sorry for the spurious closing. [~lidavidm] 's PR is just a temporary workaround, but this should be cleanly fixed on the Rust side.</pre>
