### ISSUE TITLE
Rust/Java incorrect serialization of Struct wrapped Int8Dictionary

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#203]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11936

Using rust, serialized datatype to a file with a schema of
{code:java}
Field { name: "val", data_type: Struct([Field { name: "val", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }{code}
Using a java client to read the serialized datatype results in a schema of
{code:java}
Schema<val: Struct<val: Utf8 not null> not null>{code}
whilst calling ArrowFileReader.loadNextBatch() results in
{code:java}
Exception in thread "main" java.util.NoSuchElementExceptionException in thread "main" java.util.NoSuchElementException at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000) at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:81) at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:99) at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:61) at org.apache.arrow.vector.ipc.ArrowReader.loadRecordBatch(ArrowReader.java:205) at org.apache.arrow.vector.ipc.ArrowFileReader.loadNextBatch(ArrowFileReader.java:153)
{code}

**Comment by alamb** [comment]
I think we have fixed this quite a while ago and there is no reproducer on the tickets. Closing
