### ISSUE TITLE
Test `local::tests::test_list_root` fails on main on macos

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2174]
Ported from https://github.com/influxdata/object_store_rs/issues/49 by @mkmik 

**Describe the bug**
```console
$ cargo test
...
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/.VolumeIcon.icns", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.30s
```

same commit works on linux

Reproducer on Linux:

```console
$ uname
Linux
$ sudo ln -s /foo /bad
$ cargo test
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/bad", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.23s

error: test failed, to rerun pass '--lib'
```

basically the problem is that in my mac (and possibly other macs), there is a broken symlink in the root dir.

```console
$ file /.VolumeIcon.icns
/.VolumeIcon.icns: broken symbolic link to System/Volumes/Data/.VolumeIcon.icns
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2174](https://github.com/apache/arrow-rs/issues/2174)
