### ISSUE TITLE
Too many open files: run all test with `cargo test` in local

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2222]
**Describe the bug**

latest commit from master, `cargo test` to test all ut.

```
failures:

---- file::serialized_reader::tests::test_peek_page_with_dictionary_page stdout ----
thread 'file::serialized_reader::tests::test_peek_page_with_dictionary_page' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', parquet/src/util/io.rs:84:50

---- file::serialized_reader::tests::test_skip_page_with_offset_index stdout ----
thread 'file::serialized_reader::tests::test_skip_page_with_offset_index' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', parquet/src/util/io.rs:84:50

---- arrow::arrow_reader::tests::test_scan_row_with_selection stdout ----
thread 'arrow::arrow_reader::tests::test_scan_row_with_selection' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', parquet/src/util/io.rs:84:50


failures:
    arrow::arrow_reader::tests::test_scan_row_with_selection
    file::serialized_reader::tests::test_peek_page_with_dictionary_page
    file::serialized_reader::tests::test_skip_page_with_offset_index

test result: FAILED. 552 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 9.53s
```
In my mac
ulimit -a
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                256
```

is there any case that need to open many files?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
Does this relate to a recent change, or has it been an issue for a while? Specifically https://github.com/apache/arrow-rs/pull/2220 keeps a fair few files around until the test finishes.

**Comment by liukun4515** [comment]
> Does this relate to a recent change, or has it been an issue for a while? Specifically #2220 keeps a fair few files around until the test finishes.

@tustvold 
I don't know how long the issue has been happening.
I working on other PR, run the test in local and find this error.

**Comment by amoeba** [comment]
This is still something I can reproduce locally but a `ulimit -n 1024` is enough to fix it. I think this issue can be closed. 

PS: This doesn't fail on CI because GitHub Actions sets `ulimit -n 1048575` on their macOS runners.
