### ISSUE TITLE
Arrow IPC integration test "generated_map_non_canonical" failure

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3460]
**Describe the bug**
There is some problem reading the Arrow Map files from the IPC format

in the reader tests: https://github.com/apache/arrow-rs/blob/81abc1a942cd13a92231f4a828077ad60fdabe36/arrow-integration-testing/tests/ipc_reader.rs#L120-L122

and the writer tests: https://github.com/apache/arrow-rs/blob/81abc1a942cd13a92231f4a828077ad60fdabe36/arrow-integration-testing/tests/ipc_writer.rs#L73-L74

**To Reproduce**
Uncomment one the lines referenced above and the test will fail like the following (looks like the names of the fields are different -- "entries" vs "some_entries")

```
Verifying /Users/alamb/Software/arrow-rs2/arrow/../testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_map_non_canonical.stream
  verifying content
thread 'read_1_0_0_littleendian' panicked at 'assertion failed: `(left == right)`
  left: `Field { name: "map_other_names", data_type: Map(Field { name: "some_entries", data_type: Struct([Field { name: "some_key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "some_value", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }`,
 right: `Field { name: "map_other_names", data_type: Map(Field { name: "entries", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }`: Arrow fields not the same', arrow-integration-test/src/lib.rs:253:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:240:23
   3: core::panicking::assert_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:203:5
   4: arrow_integration_test::ArrowJsonField::equals_field
             at /Users/alamb/Software/arrow-rs2/arrow-integration-test/src/lib.rs:253:17
   5: arrow_integration_test::ArrowJsonSchema::equals_schema
             at /Users/alamb/Software/arrow-rs2/arrow-integration-test/src/lib.rs:217:17
   6: arrow_integration_test::ArrowJson::equals_reader
             at /Users/alamb/Software/arrow-rs2/arrow-integration-test/src/lib.rs:166:13
   7: ipc_reader::verify_arrow_stream
             at ./tests/ipc_reader.rs:218:17
   8: ipc_reader::read_1_0_0_littleendian::{{closure}}
             at ./tests/ipc_reader.rs:140:9
   9: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/slice/iter/macros.rs:211:21
  10: ipc_reader::read_1_0_0_littleendian
             at ./tests/ipc_reader.rs:138:5
  11: ipc_reader::read_1_0_0_littleendian::{{closure}}
             at ./tests/ipc_reader.rs:109:1
  12: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
```
**Expected behavior**

**Additional context**
Found on https://github.com/apache/arrow-rs/pull/3427

**Comment by alamb** [comment]
Thanks @askoa  -- I think the ask here is to figure out what should be done with the test case.

Given the dataset has "non_canonical" in the name I suspect there is some corner case it is meant to sort out (perhaps the names should be normalized as part of the arrow ipc reader?)

**Comment by alamb** [comment]
I do not -- the C++ would be the one I would expect

**Comment by alamb** [comment]
> Other approach is to enable Archery tests for Rust for littleendian folder and remove the tests from the newly written integration tests.

I think the idea of using the existing archery tests from the overall integration suite would be a great improvement 👍

**Comment by alamb** [comment]
Thank you for the thorough research @askoa
