### ISSUE TITLE
`object_store` fails on path with space. 

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow-rs#4843]
**Describe the bug**
I assume this is related to the space in the path. If we try to get metadata on a file in a public dataset. One path (without spaces succeeds), but a file in the same bucket that contains spaces in the path fails.

**To Reproduce**
```rust
use object_store::aws::{AmazonS3Builder, AmazonS3ConfigKey};
use object_store::ObjectStore;

#[tokio::main(flavor = "current_thread")]
pub async fn run() -> Option<()> {
    let mut builder = AmazonS3Builder::from_env();

    builder = builder.with_config(AmazonS3ConfigKey::Region, "us-east-1");
    builder = builder.with_bucket_name("nyc-tlc");

    let store = builder.build().unwrap();

    // THIS WORKS
    let path= object_store::path::Path::parse("misc/FOIL_2017-12-04.csv").unwrap();
    let out = store.head(&path).await.unwrap();
    dbg!(out);
    /// out = ObjectMeta {
    //     location: Path {
    //         raw: "misc/FOIL_2017-12-04.csv",
    //     },
    //     last_modified: 2017-12-05T19:45:41Z,
    //     size: 555893670,
    //     e_tag: Some(
    //         "\"f21b9424ed28661676114566b3cf6449-34\"",
    //     ),

    // THIS DOESN'T
    let path= object_store::path::Path::parse("trip data/fhv_tripdata_2015-01.parquet").unwrap();
    let out = store.head(&path).await.unwrap();


    Some(())
}
```

**Expected behavior**
To return the metadata of the object.

**Additional context**
Public dataset: https://registry.opendata.aws/nyc-tlc-trip-records-pds/

## Backtrace:

```
thread 'main' panicked at src/issue.rs:36:43:
called `Result::unwrap()` on an `Err` value: NotFound { path: "misc", source: Error { retries: 0, message: "No Body", source: Some(reqwest::Error { kind: Status(404), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("s3.us-east-1.amazonaws.com")), port: None, path: "/nyc-tlc/misc", query: None, fragment: None } }), status: Some(404) } }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/result.rs:1077:23
   4: memcheck::issue::run::{{closure}}
             at ./src/issue.rs:36:19
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/future/future.rs:125:9
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:665:57
   7: tokio::runtime::coop::with_budget
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:665:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:410:19
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:664:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:68
  13: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  14: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:270:16
  16: std::thread::local::LocalKey<T>::with
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/std/src/thread/local.rs:246:9
  17: tokio::runtime::context::set_scheduler
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:743:27
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:652:19
  20: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  21: tokio::runtime::context::runtime::enter_runtime
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  23: tokio::runtime::runtime::Runtime::block_on
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:347:47
  24: memcheck::issue::run
             at ./src/issue.rs:49:5
  25: memcheck::main::{{closure}}
             at ./src/main.rs:15:18
  26: memcheck::main
             at ./src/main.rs:15:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/734a0d0aa0d5cab60f94f6d0c6a014dae12915f1/library/core/src/ops/function.rs:250:5

```

**Comment by tustvold** [comment]
I can't seem to reproduce this?

```
use object_store::aws::AmazonS3Builder;
use object_store::path::Path;
use object_store::ObjectStore;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let store = AmazonS3Builder::from_env()
        .with_region("us-east-1")
        .with_bucket_name("nyc-tlc")
        .build().unwrap();

    let path= Path::parse("trip data/fhv_tripdata_2015-01.parquet").unwrap();
    println!("{path}");
    let out = store.head(&path).await.unwrap();
    println!("{out:?}")
}
```

Produces

```
trip data/fhv_tripdata_2015-01.parquet
ObjectMeta { location: Path { raw: "trip data/fhv_tripdata_2015-01.parquet" }, last_modified: 2022-05-11T15:17:58Z, size: 12111775, e_tag: Some("\"b0e0c7c7a405628e767ec5de31f7595a\"") }
```

**Comment by ritchie46** [comment]
Hmm.. I believe something goes fishy here. Sorry for wasting your time. :/
