### ISSUE TITLE
LocalStack Tests Flaky in CI

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5283]
**Describe the bug**

* https://github.com/apache/arrow-rs/actions/runs/7420960113/job/20193342943
* https://github.com/apache/arrow-rs/actions/runs/7420960113/job/20193515256
* https://github.com/apache/arrow-rs/actions/runs/7420960113/job/20193722235

My suspicion is the container is running out of memory or otherwise crashing, but I have not been able to reproduce this locally

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
Error in https://github.com/apache/arrow-rs/actions/runs/7422271983/job/20197235081?pr=5285

```
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/http/asgi.py", line 548, in handle_http
    await response.write(packet)
  File "/opt/code/localstack/localstack/http/asgi.py", line 302, in write
    await self.send({"type": "http.response.body", "body": data, "more_body": True})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 179, in app_send
    await self.send(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 136, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event
    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

**Comment by tustvold** [comment]
Filed an upstream issue as I'm somewhat at a loss for how to debug this further - https://github.com/localstack/localstack/issues/10003

**Comment by bentsku** [comment]
Okay I finally could reproduce and find which requests were triggering the issue:
I could reproduce by creating a pretty resource-constrained environment (Docker image with 0.5 CPUs)

It's a `GetObject` with `Content-Length` set to 1, with the key prefix `RACE-`
Followed by a `PutObject` of length 2.
The first call get the entirety of the data with an indicated content-length of 1, but gets `10` so it fails. 
The reproducer is not stable at all, I just run `cargo test aws::tests::s3_test --features aws -- --exact` again and again and it can fail around 2 to 10% of the time with 0.5CPU. 

I'll work on a fix now, might have an idea where this could come from. Thanks again for reporting this, I'm sure we will finally get to the end of this! 🤞

**Comment by tustvold** [comment]
Fantastic news, I'll probably wait until `3.3` as the regular CI failures appear to have abated for now, but will pre-empt this and use a image sha should they return
