### ISSUE TITLE
IPC reader panicks with out of bounds error

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#541]
**Describe the bug**

I am working on [a PR in DataFusion](https://github.com/apache/arrow-datafusion/pull/709) and hit this during query execution. 

```
thread 'tokio-runtime-worker' panicked at 'range end index 51144 out of range for slice of length 49000', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.4.0/src/ipc/reader.rs:42:21
```

**To Reproduce**
I don't have a repro case yet. I will try and create one.

**Expected behavior**
Don't panick.

**Additional context**
None

**Comment by andygrove** [comment]
I just saw some more context for this, so maybe not truly an Arrow IPC bug after all (although it would be nice to avoid the panic).

```
[2021-07-13T00:53:57Z INFO  ballista_executor::flight_service] FetchPartition PartitionId { job_id: "IuNhtqp", stage_id: 1, partition_id: 1 } reading /tmp/.tmpu1eS3W/IuNhtqp/1/1/data.arrow
[2021-07-13T00:53:57Z WARN  ballista_executor::flight_service] Error streaming results: Status { code: Internal, message: "ArrowError: IoError(\"failed to fill whole buffer\")" }
```

**Comment by andygrove** [comment]
I have a repro case with a 2MB IPC file

**Comment by andygrove** [comment]
```
thread 'tokio-runtime-worker' panicked at 'range end index 51144 out of range for slice of length 49000', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.4.0/src/ipc/reader.rs:42:21
stack backtrace:
   0:     0x55886acee290 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55886acee290 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55886acee290 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55886acee290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55886ad127cf - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55886ace8595 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55886acf084b - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55886acf084b - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55886acf084b - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55886acf031d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55886acf0e5d - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55886acf09f7 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x55886acee72c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55886acf0959 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x558869f0e491 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x558869f0e682 - core::slice::index::slice_end_index_len_fail::hd279a020961a5d28
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/slice/index.rs:41:5
  16:     0x55886ab70598 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h96fc46156afd4786
  17:     0x55886aa64ab2 - arrow::ipc::reader::create_array::h51b477fa0b7ed975
  18:     0x55886aa6987e - arrow::ipc::reader::read_record_batch::hea6f1b2225384031
  19:     0x55886a09412d - <arrow::ipc::reader::FileReader<R> as core::iter::traits::iterator::Iterator>::next::ha6974b73b82470a3
  20:     0x55886a072e33 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfd74ebb4f5544b8f
  21:     0x55886a095c21 - tokio::runtime::task::harness::poll_future::hbf927d6278c69d82
  22:     0x55886a095ec2 - tokio::runtime::task::harness::Harness<T,S>::poll::h06844f434726e106
  23:     0x55886a9a53b2 - std::thread::local::LocalKey<T>::with::hdf0f7e2cffb9cca7
  24:     0x55886a9c158a - tokio::runtime::thread_pool::worker::Context::run_task::h96fcb0e955022e88
  25:     0x55886a9c0763 - tokio::runtime::thread_pool::worker::Context::run::h4ba1c4818ac70106
  26:     0x55886a9a6b05 - tokio::macros::scoped_tls::ScopedKey<T>::set::h38b5613b61fed270
  27:     0x55886a9c01d2 - tokio::runtime::thread_pool::worker::run::h9d87413bc8c002e8
  28:     0x55886a9ca56e - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h2e40e7478a3cb9f5
  29:     0x55886a9ac605 - std::panicking::try::hda54480cbbb459f9
  30:     0x55886a9bc5a3 - tokio::runtime::task::harness::Harness<T,S>::poll::h206460627d87f644
  31:     0x55886a9b2e7a - std::sys_common::backtrace::__rust_begin_short_backtrace::hd08015b3d11daec5
  32:     0x55886a9c8f68 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4cad2e4d517fce10
  33:     0x55886acf47ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75c2ca1daad47228
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  34:     0x55886acf47ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf9f8afc9d34e311
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  35:     0x55886acf47ba - std::sys::unix::thread::Thread::new::thread_start::hc238bac7748b195d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  36:     0x7f9bce3206db - start_thread
  37:     0x7f9bcdaa771f - __clone
  38:                0x0 - <unknown>
```

**Comment by jorgecarleitao** [comment]
Could you upload the file?

**Comment by andygrove** [comment]
I've uploaded it to Google Drive: https://drive.google.com/file/d/1C7h_VE6F3PrChyOf3lkUrUmA33kmdowm/view?usp=sharing

**Comment by andygrove** [comment]
Sorry for the noise. It looks like I had two threads writing to the same file.
