### ISSUE TITLE
CI Failure in json writer tests after upgrade from lexical-core 1.0.2 to lexical-core 1.0.3: `range end index 20 out of range for slice of length 19`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6858]
**Describe the bug**

CI is failing on main, apparently related to the upgrade from lexical-core 1.0.2 to lexical-core 1.0.3

https://github.com/apache/arrow-rs/actions/runs/12216285082/job/34079214477

```
---- writer::tests::test_write_single_batch stdout ----
thread 'writer::tests::test_write_single_batch' panicked at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-write-integer-1.0.4/src/jeaiii.rs:304:29:
range end index 20 out of range for slice of length 19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- writer::tests::test_write_multi_batches stdout ----
thread 'writer::tests::test_write_multi_batches' panicked at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-write-integer-1.0.4/src/jeaiii.rs:304:29:
range end index 20 out of range for slice of length 19

---- writer::tests::write_arrays stdout ----
thread 'writer::tests::write_arrays' panicked at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-write-integer-1.0.4/src/jeaiii.rs:304:29:
range end index 20 out of range for slice of length 19

---- writer::tests::write_basic_rows stdout ----
thread 'writer::tests::write_basic_rows' panicked at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-write-integer-1.0.4/src/jeaiii.rs:304:29:
range end index 20 out of range for slice of length 19


failures:
    writer::tests::test_write_multi_batches
    writer::tests::test_write_single_batch
    writer::tests::write_arrays
    writer::tests::write_basic_rows
```

**To Reproduce**
```shell
# update to get lexical-core 1.0.3
cargo update
cargo test -p arrow-json --lib
```

**Expected behavior**
Tests should pass

**Additional context**
- @jayzhan211  observed this downstream in DataFusion: https://github.com/apache/datafusion/issues/13686
- @jonahgao  fixed by pinning the lexical core version: https://github.com/apache/datafusion/pull/13689
- Upstream ticket filed: https://github.com/Alexhuszagh/rust-lexical/issues/191

**Comment by alamb** [comment]
I am pretty sure this is a regression in upstream lexical-core

I filed an upstream ticket (with reproducer): https://github.com/Alexhuszagh/rust-lexical/issues/191

**Comment by alamb** [comment]
https://github.com/Alexhuszagh/rust-lexical/issues/191 has been fixed upstream ❤️
